version: '3.1'

# Description: Build and run local development copy of SIR

services:
  indexer:
    build: build/sir-dev
    env_file:
      - ./default/postgres.env
    volumes:
      - ${SIR_LOCAL_ROOT:-../sir}:/code
      - ${SIR_CONFIG_PATH:-./default/indexer.ini}:/code/config.ini
    depends_on:
      - db
      - mq
      - search
